### PR TITLE
Swift: fix Xcode build on Big Sur

### LINKED ISSUE #84: Build for iOS failing
I understand that this is an internal project for development, but I am trying to build this for exploration purposes. I am able to get the project to build and operate properly for Swift in macOS, but builds for iOS fail. The Swift documentation state the project is 'set up as a CocoaPod for integration into the Signal iOS client', so I believe iOS builds should succeed. The fact that macOS builds are successful suggests to me this is not a problem with my local Rust set up, but I'm happy to be corrected.

Steps to recreate:
1) Using macOS Big Sur 11.0.1, Xcode 12.2, iOS 14.2.
2) Create a new iOS project using Swift
3) Use `pod init`
4) Add 'pod 'SignalClient', git: 'https://github.com/signalapp/libsignal-client.git' to the pod file
5) `pod install`
6) Try to build for an iOS target.

The error I'm getting is below, and appears to occur during linking whilst compiling get random.

cargo build -p libsignal-ffi --release
   Compiling proc-macro2 v1.0.24
   Compiling syn v1.0.45
   Compiling libc v0.2.79
   Compiling getrandom v0.1.15

error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-m64" "-arch" "x86_64" "-L" "/Users/matthewroche/.rustup/toolchains/nightly-2020-11-09-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Users/matthewroche/Library/Developer/Xcode/DerivedData/SignalMapsIos-hghgpvfhvntzmveekioanzymzyfq/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SignalClient.build/DerivedSources/libsignal-ffi/release/build/syn-d54f49b28eca3f98/build_script_build-d54f49b28eca3f98.build_script_build.i1lvbqlc-cgu.0.rcgu.o" "/Users/matthewroche/Library/Developer/Xcode/DerivedData/SignalMapsIos-hghgpvfhvntzmveekioanzymzyfq/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SignalClient.build/DerivedSources/libsignal-ffi/release/build/syn-d54f49b28eca3f98/build_script_build-d54f49b28eca3f98.build_script_build.i1lvbqlc-cgu.1.rcgu.o" "/Users/matthewroche/Library/Developer/Xcode/DerivedData/SignalMapsIos-hghgpvfhvntzmveekioanzymzyfq/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SignalClient.build/DerivedSources/libsignal-ffi/release/build/syn-d54f49b28eca3f98/build_script_build-d54f49b28eca3f98.build_script_build.i1lvbqlc-cgu.10.rcgu.o" "/Users/matthewroche/Library/Developer/Xcode/DerivedData/SignalMapsIos-hghgpvfhvntzmveekioanzymzyfq/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SignalClient.build/DerivedSources/libsignal-ffi/release/build/syn-d54f49b28eca3f98/build_script_build-d54f49b28eca3f98.build_script_build.i1lvbqlc-cgu.11.rcgu.o" "/Users/matthewroche/Library/Developer/Xcode/DerivedData/SignalMapsIos-hghgpvfhvntzmveekioanzymzyfq/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SignalClient.build/DerivedSources/libsignal-ffi/release/build/syn-d54f49b28eca3f98/build_script_build-d54f49b28eca3f98.build_script_build.i1lvbqlc-cgu.12.rcgu.o" "/Users/matthewroche/Library/Developer/Xcode/DerivedData/SignalMapsIos-hghgpvfhvntzmveekioanzymzyfq/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SignalClient.build/DerivedSources/libsignal-ffi/release/build/syn-d54f49b28eca3f98/build_script_build-d54f49b28eca3f98.build_script_build.i1lvbqlc-cgu.13.rcgu.o" "/Users/matthewroche/Library/Developer/Xcode/DerivedData/SignalMapsIos-hghgpvfhvntzmveekioanzymzyfq/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SignalClient.build/DerivedSources/libsignal-ffi/release/build/syn-d54f49b28eca3f98/build_script_build-d54f49b28eca3f98.build_script_build.i1lvbqlc-cgu.14.rcgu.o" "/Users/matthewroche/Library/Developer/Xcode/DerivedData/SignalMapsIos-hghgpvfhvntzmveekioanzymzyfq/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SignalClient.build/DerivedSources/libsignal-ffi/release/build/syn-d54f49b28eca3f98/build_script_build-d54f49b28eca3f98.build_script_build.i1lvbqlc-cgu.15.rcgu.o" "/Users/matthewroche/Library/Developer/Xcode/DerivedData/SignalMapsIos-hghgpvfhvntzmveekioanzymzyfq/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SignalClient.build/DerivedSources/libsignal-ffi/release/build/syn-d54f49b28eca3f98/build_script_build-d54f49b28eca3f98.build_script_build.i1lvbqlc-cgu.2.rcgu.o" "/Users/matthewroche/Library/Developer/Xcode/DerivedData/SignalMapsIos-hghgpvfhvntzmveekioanzymzyfq/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SignalClient.build/DerivedSources/libsignal-ffi/release/build/syn-d54f49b28eca3f98/build_script_build-d54f49b28eca3f98.build_script_build.i1lvbqlc-cgu.3.rcgu.o" "/Users/matthewroche/Library/Developer/Xcode/DerivedData/SignalMapsIos-hghgpvfhvntzmveekioanzymzyfq/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SignalClient.build/DerivedSources/libsignal-ffi/release/build/syn-d54f49b28eca3f98/build_script_build-d54f49b28eca3f98.build_script_build.i1lvbqlc-cgu.4.rcgu.o" "/Users/matthewroche/Library/Developer/Xcode/DerivedData/SignalMapsIos-hghgpvfhvntzmveekioanzymzyfq/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SignalClient.build/DerivedSources/libsignal-ffi/release/build/syn-d54f49b28eca3f98/build_script_build-d54f49b28eca3f98.build_script_build.i1lvbqlc-cgu.5.rcgu.o" "/Users/matthewroche/Library/Developer/Xcode/DerivedData/SignalMapsIos-hghgpvfhvntzmveekioanzymzyfq/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SignalClient.build/DerivedSources/libsignal-ffi/release/build/syn-d54f49b28eca3f98/build_script_build-d54f49b28eca3f98.build_script_build.i1lvbqlc-cgu.6.rcgu.o" "/Users/matthewroche/Library/Developer/Xcode/DerivedData/SignalMapsIos-hghgpvfhvntzmveekioanzymzyfq/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SignalClient.build/DerivedSources/libsignal-ffi/release/build/syn-d54f49b28eca3f98/build_script_build-d54f49b28eca3f98.build_script_build.i1lvbqlc-cgu.7.rcgu.o" "/Users/matthewroche/Library/Developer/Xcode/DerivedData/SignalMapsIos-hghgpvfhvntzmveekioanzymzyfq/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SignalClient.build/DerivedSources/libsignal-ffi/release/build/syn-d54f49b28eca3f98/build_script_build-d54f49b28eca3f98.build_script_build.i1lvbqlc-cgu.8.rcgu.o" "/Users/matthewroche/Library/Developer/Xcode/DerivedData/SignalMapsIos-hghgpvfhvntzmveekioanzymzyfq/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SignalClient.build/DerivedSources/libsignal-ffi/release/build/syn-d54f49b28eca3f98/build_script_build-d54f49b28eca3f98.build_script_build.i1lvbqlc-cgu.9.rcgu.o" "-o" "/Users/matthewroche/Library/Developer/Xcode/DerivedData/SignalMapsIos-hghgpvfhvntzmveekioanzymzyfq/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SignalClient.build/DerivedSources/libsignal-ffi/release/build/syn-d54f49b28eca3f98/build_script_build-d54f49b28eca3f98" "/Users/matthewroche/Library/Developer/Xcode/DerivedData/SignalMapsIos-hghgpvfhvntzmveekioanzymzyfq/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SignalClient.build/DerivedSources/libsignal-ffi/release/build/syn-d54f49b28eca3f98/build_script_build-d54f49b28eca3f98.3bm18redto8u1wev.rcgu.o" "-Wl,-dead_strip" "-nodefaultlibs" "-L" "/Users/matthewroche/Library/Developer/Xcode/DerivedData/SignalMapsIos-hghgpvfhvntzmveekioanzymzyfq/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SignalClient.build/DerivedSources/libsignal-ffi/release/deps" "-L" "/Users/matthewroche/.rustup/toolchains/nightly-2020-11-09-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Users/matthewroche/.rustup/toolchains/nightly-2020-11-09-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libstd-ff8f19287472ab25.rlib" "/Users/matthewroche/.rustup/toolchains/nightly-2020-11-09-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libpanic_unwind-e3d969bfc9686736.rlib" "/Users/matthewroche/.rustup/toolchains/nightly-2020-11-09-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libobject-938ee2d2dbaf220c.rlib" "/Users/matthewroche/.rustup/toolchains/nightly-2020-11-09-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libaddr2line-9bae58925fa3dd0b.rlib" "/Users/matthewroche/.rustup/toolchains/nightly-2020-11-09-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libgimli-2ec940c1e1a44ce7.rlib" "/Users/matthewroche/.rustup/toolchains/nightly-2020-11-09-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_demangle-a190fa5b69d68147.rlib" "/Users/matthewroche/.rustup/toolchains/nightly-2020-11-09-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libhashbrown-b4be29ebbc3c6d64.rlib" "/Users/matthewroche/.rustup/toolchains/nightly-2020-11-09-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_alloc-7798de3537b0376b.rlib" "/Users/matthewroche/.rustup/toolchains/nightly-2020-11-09-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libunwind-059af72ed835e91e.rlib" "/Users/matthewroche/.rustup/toolchains/nightly-2020-11-09-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcfg_if-40807d6e6f06e462.rlib" "/Users/matthewroche/.rustup/toolchains/nightly-2020-11-09-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liblibc-ff818040cbe57af0.rlib" "/Users/matthewroche/.rustup/toolchains/nightly-2020-11-09-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liballoc-3dc0396c7b6c0532.rlib" "/Users/matthewroche/.rustup/toolchains/nightly-2020-11-09-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_core-465082706ea1ede1.rlib" "/Users/matthewroche/.rustup/toolchains/nightly-2020-11-09-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcore-e3cd79f6ad1173fd.rlib" "/Users/matthewroche/.rustup/toolchains/nightly-2020-11-09-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcompiler_builtins-e0d54f11f476b2b7.rlib" "-lSystem" "-lresolv" "-lc" "-lm"
  = note: ld: library not found for -lSystem
          clang: error: linker command failed with exit code 1 (use -v to see invocation)

If I go to the folder containing the Pod files in terminal and run `cargo build -p libsignal-ffi --release` then the build is successful, which makes me wonder if this is related to the environment Xcode builds in, but I have been unable to identify a fix after days of searching. I've attached build logs below.

[Build target SignalClient_2020-11-26T14-28-00.txt](https://github.com/signalapp/libsignal-client/files/5603996/Build.target.SignalClient_2020-11-26T14-28-00.txt)

I realise this is unsupported, but would be grateful for any assistance.

### PR DESCRIPTION
**Pull request by jrose-signal**
Rust build scripts and proc-macros are compiled for the host, rather than the target, which means they need a search path to link against the host's libraries. macOS Big Sur doesn't provide that in the default search paths anymore, so we add one manually based on an environment variable provided by Xcode.

Fixes #84.

### CODE REVIEW

File: swift/build_ffi.sh [hunk 1]
```diff
@@ -42,5 +42,13 @@ done
 
 check_rust
 
+if [[ -n "${DEVELOPER_SDK_DIR:-}" ]]; then
+  # Assume we're in Xcode, which means we're probably cross-compiling.
+  # In this case, we need to add an extra library search path for build scripts and proc-macros,
+  # which run on the host instead of the target.
+  # (macOS Big Sur does not have linkable libraries in /usr/lib/.)
+  export LIBRARY_PATH="${DEVELOPER_SDK_DIR}/MacOSX.sdk/usr/lib:${LIBRARY_PATH:-}"
```
Comment (jack-signal) [inline swift/build_ffi.sh:50]: Why `${LIBRARY_PATH:-}` and not just `${LIBRARY_PATH}` - both have same effect if unset right? Just wondering if I am missing something about this.

**Review by jack-signal — APPROVED** [review]

File: swift/build_ffi.sh (hunk 1 above)
Comment (jrose-signal) [reply swift/build_ffi.sh:50]: `set -u` at the top of the script makes bash error on undefined environment variables, but otherwise yeah.
